### ISSUE TITLE
Possibilité d'utiliser la license LPRàB ?

### ISSUE THREAD

**Issue by L-Sherry** [bnjbvr/rouille#10]
Je propose de changer la licence de ce logiciel pour la licence publique [Rien à Branler](http://sam.zoy.org/lprab/). C'est une traduction française de la licence WTFPL, qui devrait être compatible avec cette dernière.

```
                LICENCE PUBLIQUE RIEN À BRANLER
                      Version 1, Mars 2009

 Copyright (C) 2009 Sam Hocevar
  14 rue de Plaisance, 75014 Paris, France
 
 La copie et la distribution de copies exactes de cette licence sont
 autorisées, et toute modification est permise à condition de changer
 le nom de la licence. 

         CONDITIONS DE COPIE, DISTRIBUTON ET MODIFICATION
               DE LA LICENCE PUBLIQUE RIEN À BRANLER

  0. Faites ce que vous voulez, j’en ai RIEN À BRANLER.
```
http://sam.zoy.org/lprab/COPYING

**Comment by bnjbvr** [comment]
Alors là je dis oui. Oui oui oui oui.

**Comment by fpeterschmitt** [comment]
![image](https://user-images.githubusercontent.com/4390126/133001550-cb87cd39-bf34-4674-8a49-259cb3389f91.png)

**Comment by TrevCan** [comment]
Ça sera fixé sur PR numéro #6
