### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by ad-m** [bnjbvr/rouille#5]
Could you provide in README about context and inspiration to create a new language? I do not know the local situation in France, and besides, even for the French, it may not be obvious after a few years.

**Comment by Firepal** [comment]
In short: This is a big joke

**Comment by ad-m** [comment]
So there is no specific action, project or behavior by the French government to inspire? Thanks for the clarification.

In Poland, we have situations where, for example, Polish administration wanted to launch cloud computing platform. They were the first to create the platform as an open-stack service. The project was not very successful. Then they created a "national cloud" where they bought locations and – from potenates –  equipment and virtualizations . Again, it turned out that the hardware and popular software itself are not of great value (in my opinion, the cloud is a logical value, billing, API, integrated ecosystem, automatic scaling, etc.). As a result, it was decided to lower the entry for potenates (Azure, GCP) by creating government evangelization for public money to use their products sold through the "public provider of cloud services" (A track similar to Rackspace, but for public money). At the same time, Poland is recognized as a huge source of skilled engineers and is undergoing a brain drain through the cost-effective development of intellectual property of foreign companies.

**Comment by bnjbvr** [comment]
Thanks, I found that information interesting! In France, there had been wills to make a "foreign operating system" in the past, which has not resulted in anything concrete other than political plays. There's still a will to create sovereign cloud infrastructure (e.g. recent [tweet in French](https://twitter.com/presseorange/status/1397822216113463296)). So this was definitely inspired from reality, but rouille itself is mostly a joke indeed, and not intended to be used in actuality.

**Comment by pabloko** [comment]
a disgusting language in a even more disgusting language... 
what a garbage waste of internet space
